export const ActionTypes = {
    GET_PRODUCT_PENDING: "GET_PRODUCT_PENDING",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",

    GET_PRODUCT_BY_ID_PENDING: "GET_PRODUCT_BY_ID_PENDING",
    GET_PRODUCT_BY_ID_SUCESS: "GET_PRODUCT_BY_ID_SUCESS",
    GET_PRODUCT_BY_ID_FAIL: "GET_PRODUCT_BY_ID_FAIL",
    GET_PRODUCT_BY_ID_RESET: "GET_PRODUCT_BY_ID_RESET",


    //cart action types
    // ADD TO CAR
    ADD_TO_CART_PENDING: "ADD_TO_CART_PENDING",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILED: "ADD_TO_CART_FAILED",

    //REMOVE FROM THE CART
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
}


export const responceTypes = {
    success: "success",
    pending: "pending",
    error: "error"
}

export const BASE_URL = ""

